export const dataArray = [
    {
      id: 1,
      title: "質問・回答の追加・編集",
      url: "/admin/handle-question",
      description: "質問・回答例を追加・編集します。",
      imgUrl: "/icon/document_icon.png",
      imgAlt: "document_icon",
    },
    {
      id: 2,
      title: "タスクの一覧",
      url: "/admin/tasks",
      description: "タスクの一覧を確認できます。",
      imgUrl: "/icon/pencil_icon.png",
      imgAlt: "pencil_icon",
    },
    {
      id: 3,
      title: "回答の閲覧",
      url: "/admin/histories",
      description: "ユーザーの回答を閲覧できます。",
      imgUrl: "/icon/search_icon.png",
      imgAlt: "search_icon",
    },
    {
      id: 4,
      title: "ユーザー管理",
      url: "/admin/users",
      description: "ユーザーの一覧を確認できます。",
      imgUrl: "/icon/user_icon.png",
      imgAlt: "user_icon",
    },
    {
      id: 5,
      title: "グループ一覧",
      url: "/admin/groups",
      description: "グループの一覧を確認できます。",
      imgUrl: "/icon/group_icon.png",
      imgAlt: "group_icon",
    },    
  ];
