// テスト用データ
export const departments = [
  {
    id: 1,
    name: "Java",
    createtdUser: "hoge",
    createdAt: new Date(),
    updateUser: "hoge",
    updateAt: new Date(),
  },
  {
    id: 2,
    name: "PHP",
    createtdUser: "hoge",
    createdAt: new Date(),
    updateUser: "hoge",
    updateAt: new Date(),
  },
  {
    id: 3,
    name: "FR",
    createtdUser: "hoge",
    createdAt: new Date(),
    updateUser: "hoge",
    updateAt: new Date(),
  },
  {
    id: 4,
    name: "CL",
    createtdUser: "hoge",
    createdAt: new Date(),
    updateUser: "hoge",
    updateAt: new Date(),
  },
  {
    id: 5,
    name: "ML",
    createtdUser: "hoge",
    createdAt: new Date(),
    updateUser: "hoge",
    updateAt: new Date(),
  },
  {
    id: 6,
    name: "QA",
    createtdUser: "hoge",
    createdAt: new Date(),
    updateUser: "hoge",
    updateAt: new Date(),
  },
];

export const tasks = [
  {
    id: 1,
    project_name: "hoge",
    department: "Java",
    question: ["hoge", "hoge", "hoge"],
    users: ["佐藤太郎", "鈴木次郎", "伊藤三郎"],
    answer_deadline: "2100-01-01",
  },
  {
    id: 2,
    project_name: "foo",
    department: "PHP",
    question: ["foo", "foo", "foo"],
    users: ["佐藤太郎", "鈴木次郎", "伊藤三郎", "田中四郎"],
    answer_deadline: "2100-01-01",
  },
  {
    id: 3,
    project_name: "bar",
    department: "FR",
    question: ["bar", "bar", "bar"],
    users: ["佐藤太郎", "鈴木次郎", "伊藤三郎"],
    answer_deadline: "2100-01-01",
  },
  {
    id: 4,
    project_name: "hogehoge",
    department: "CL",
    question: ["hogehoge", "hogehoge", "hogehoge"],
    users: ["佐藤太郎", "鈴木次郎", "伊藤三郎"],
    answer_deadline: "2200-01-01",
  },
  {
    id: 5,
    project_name: "foofoo",
    department: "ML",
    question: ["foofoo", "foofoo", "foofoo"],
    users: ["佐藤太郎", "鈴木次郎", "伊藤三郎", "田中四郎"],
    answer_deadline: "2200-01-01",
  },
  {
    id: 6,
    project_name: "barbar",
    department: "QA",
    question: ["barbar", "barbar", "barbar"],
    users: ["佐藤太郎", "鈴木次郎", "伊藤三郎"],
    answer_deadline: "2200-01-01",
  },
];
