export const metadata = {
    title: "match-face admin/histories",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
        <>
        <div>{children}</div>
        </>
    );
  }
  